TIPO_PRODUTO_CHILENO = "CHILENO"
TIPO_PRODUTO_TOLUENO = "TOLUENO"
TIPO_PRODUTO_HEXANO = "HEXANO"
TIPO_PRODUTO_BENZENO = "BENZENO"
TIPO_PRODUTO_SOLVENTE_C6 = "SOLVENTE_C6"
TIPO_PRODUTO_AGUARRAS = "AGUARRAS"
TIPO_PRODUTO_GASOLINA = "GASOLINA"
TIPO_PRODUTO_METANOL = "METANOL"
TIPO_PRODUTO_ETANOL = "ETANOL"
TIPO_PRODUTO_GLICERINA = "GLICERINA"
TIPO_PRODUTO_BIODIESEL = "BIODIESEL"
TIPO_PRODUTO_ESTIRENO = "ESTIRENO"
TIPO_PRODUTO_OLEO_DIESEL = "OLEO_DIESEL"
TIPO_PRODUTO_OLEO_MINERAL = "OLEO_MINERAL"

TIPOS_PRODUTOS = (
    (TIPO_PRODUTO_CHILENO, "Chileno"),
    (TIPO_PRODUTO_TOLUENO, "Tolueno"),
    (TIPO_PRODUTO_HEXANO, "Hexano"),
    (TIPO_PRODUTO_BENZENO, "Benzeno"),
    (TIPO_PRODUTO_SOLVENTE_C6, "Solvente C6"),
    (TIPO_PRODUTO_AGUARRAS, "Aguarrás"),
    (TIPO_PRODUTO_GASOLINA, "Gasolina"),
    (TIPO_PRODUTO_METANOL, "Metanol"),
    (TIPO_PRODUTO_ETANOL, "Etanol"),
    (TIPO_PRODUTO_GLICERINA, "Glicerina"),
    (TIPO_PRODUTO_BIODIESEL, "Biodiesel"),
    (TIPO_PRODUTO_ESTIRENO, "Estireno"),
    (TIPO_PRODUTO_OLEO_DIESEL, "Óleo Diesel"),
    (TIPO_PRODUTO_OLEO_MINERAL, "Óleo Mineral"),
)

FRETE_ESTADO_EM_ANALISE = "EM_ANALISE"
FRETE_ESTADO_RECUSADO = "RECUSADO"
FRETE_ESTADO_AGUARDANDO_COLETA = "AGUARDANDO_COLETA"
FRETE_ESTADO_EM_ANDAMENTO = "EM_ANDAMENTO"
FRETE_ESTADO_FINALIZADO = "FINALIZADO"

FRETES_ESTADOS = (
    (FRETE_ESTADO_EM_ANALISE, "Em análise"),
    (FRETE_ESTADO_RECUSADO, "Recusado"),
    (FRETE_ESTADO_AGUARDANDO_COLETA, "Aguardando coleta"),
    (FRETE_ESTADO_EM_ANDAMENTO, "Em andamento"),
    (FRETE_ESTADO_FINALIZADO, "Finalizado"),
)

RESERVATORIO_MATERIAL_ACO = "ACO"
RESERVATORIO_MATERIAL_ALUMINIO = "ALUMINIO"

RESERVATORIOS_MATERIAIS = (
    (RESERVATORIO_MATERIAL_ACO, "Aço"),
    (RESERVATORIO_MATERIAL_ALUMINIO, "Alumínio"),
)
